"""Command-line entry point for Founder."""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from datetime import date
from pathlib import Path

from founder.config import load_eodhd_config
from founder.http import EodhdClient
from founder.logging import get_logger, setup_logging
from founder.pipeline import run_dry_run
from founder.workflows import (
    generated_run_id,
    run_bronze_workflow,
    run_evaluate_workflow,
    run_gold_workflow,
    run_refresh_workflow,
    run_search_sync_isins_workflow,
    run_search_workflow,
    run_silver_workflow,
)

DEFAULT_ROOT = Path("lake")
DEFAULT_SEARCH_INPUT = Path("docs/eodhd_ucits_etf_matches.csv")
LOGGER = get_logger(__name__)


def _parse_date(value: str) -> date:
    return date.fromisoformat(value)


def _positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("value must be at least 1")
    return parsed


def _positive_float(value: str) -> float:
    parsed = float(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be positive")
    return parsed


def _target_returns(value: str) -> list[float]:
    return [float(item.strip()) for item in value.split(",") if item.strip()]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Founder portfolio data tooling.")
    parser.add_argument("--debug", action="store_true", help="Write verbose DEBUG logs.")
    subparsers = parser.add_subparsers(dest="command")
    search = subparsers.add_parser("search", help="Run Search for a discovery query.")
    search.add_argument(
        "--debug",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Write verbose DEBUG logs.",
    )
    search.add_argument(
        "query", help="Search string to find in candidate names, for example UCITS ETF."
    )
    search.add_argument(
        "--root", default=str(DEFAULT_ROOT), help="Lake root for generated artifacts."
    )
    search.add_argument(
        "--input",
        default=str(DEFAULT_SEARCH_INPUT),
        help="CSV/JSON candidate source. Defaults to the checked-in UCITS ETF dataset.",
    )
    search.add_argument(
        "--search-run-id",
        help="Optional stable identifier. Generated from query and date by default.",
    )
    search.add_argument("--run-date", type=_parse_date, help="Optional search run date YYYY-MM-DD.")
    search.add_argument(
        "--no-approve", action="store_true", help="Do not approve the generated canonical universe."
    )
    sync_eodhd_isins = subparsers.add_parser(
        "sync-eodhd-isins",
        help="Fetch all EODHD symbol-list rows with ISINs and approve the canonical universe.",
    )
    sync_eodhd_isins.add_argument(
        "--debug",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Write verbose DEBUG logs.",
    )

    def add_selection_parser(name: str, help_text: str) -> argparse.ArgumentParser:
        selection = subparsers.add_parser(name, help=help_text)
        selection.add_argument(
            "--debug",
            action="store_true",
            default=argparse.SUPPRESS,
            help="Write verbose DEBUG logs.",
        )
        selection.add_argument(
            "--root", default=str(DEFAULT_ROOT), help="Lake root containing current_universe.json."
        )
        selection.add_argument(
            "--run-id", help="Optional stable identifier. Generated by date by default."
        )
        selection.add_argument(
            "--start-date",
            type=_parse_date,
            help="Optional selection start date YYYY-MM-DD. Omitted by default for full history.",
        )
        selection.add_argument(
            "--end-date", type=_parse_date, help="Optional selection end date YYYY-MM-DD."
        )
        selection.add_argument("--run-date", type=_parse_date, help="Archive run date YYYY-MM-DD.")
        selection.add_argument(
            "--concurrency",
            type=_positive_int,
            default=2,
            help="Maximum parallel EODHD selection workers. Defaults to 2 for cron-safe runs.",
        )
        selection.add_argument(
            "--mock",
            action="store_true",
            help="Write mocked quote outputs after planning.",
        )
        selection_selector = selection.add_mutually_exclusive_group()
        selection_selector.add_argument(
            "--limit",
            type=_positive_int,
            help="Limit Selection to the first N approved canonical ISINs.",
        )
        selection_selector.add_argument(
            "--isin",
            help="Limit Selection to one approved canonical ISIN.",
        )
        return selection

    add_selection_parser("selection", "Run Selection loading for the approved universe.")
    silver = subparsers.add_parser(
        "silver", help="Build Silver quote files from Selection outputs."
    )
    silver.add_argument(
        "--debug",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Write verbose DEBUG logs.",
    )
    silver.add_argument("--root", default=str(DEFAULT_ROOT), help="Lake root to build from.")
    silver.add_argument(
        "--concurrency",
        type=_positive_int,
        default=2,
        help="Maximum parallel Silver workers. Defaults to 2 for 4-core hosts.",
    )
    gold = subparsers.add_parser("gold", help="Build Gold risk inputs from Silver quotes.")
    gold.add_argument(
        "--debug",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Write verbose DEBUG logs.",
    )
    gold.add_argument("--root", default=str(DEFAULT_ROOT), help="Lake root to build from.")
    gold.add_argument(
        "--concurrency",
        type=_positive_int,
        default=2,
        help="Maximum parallel Gold workers. Defaults to 2 for 4-core hosts.",
    )
    evaluate = subparsers.add_parser("evaluate", help="Build evaluation and portfolio outputs.")
    evaluate.add_argument(
        "--debug",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Write verbose DEBUG logs.",
    )
    evaluate.add_argument("--root", default=str(DEFAULT_ROOT), help="Lake root to evaluate.")
    evaluate.add_argument("--evaluation-id", default="default", help="Stable evaluation id.")
    evaluate.add_argument("--portfolio-id", default="equal-weight", help="Stable portfolio id.")
    evaluate.add_argument(
        "--objective",
        default="equal_weight",
        help="Optimization objective such as minimum_variance or risk_parity.",
    )
    evaluate.add_argument("--optimize", action="store_true", help="Write optimized weights.")
    evaluate.add_argument("--walk-forward", action="store_true", help="Write walk-forward outputs.")
    evaluate.add_argument("--rebalance", action="store_true", help="Write rebalance events.")
    evaluate.add_argument(
        "--frontier", action="store_true", help="Write efficient-frontier outputs."
    )
    evaluate.add_argument("--tail-risk", action="store_true", help="Write tail-risk outputs.")
    evaluate.add_argument("--run-id", default="evaluation-run", help="Run id for optional outputs.")
    evaluate.add_argument("--train-window", type=_positive_int, default=2)
    evaluate.add_argument("--test-window", type=_positive_int, default=1)
    evaluate.add_argument("--schedule", default="monthly")
    evaluate.add_argument("--grid-step", type=_positive_float, default=0.1)
    evaluate.add_argument("--max-weight", type=_positive_float, default=1.0)
    evaluate.add_argument("--target-returns", type=_target_returns, default=[0.0, 0.01])
    evaluate.add_argument("--confidence-level", type=float, default=0.95)
    refresh = subparsers.add_parser("refresh", help="Run Selection, Silver, and Gold in order.")
    refresh.add_argument(
        "--debug",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Write verbose DEBUG logs.",
    )
    refresh.add_argument(
        "--root", default=str(DEFAULT_ROOT), help="Lake root containing current_universe.json."
    )
    refresh.add_argument(
        "--run-id", help="Optional stable identifier. Generated by date by default."
    )
    refresh.add_argument(
        "--start-date",
        type=_parse_date,
        help="Optional bronze start date YYYY-MM-DD. Omitted by default for full history.",
    )
    refresh.add_argument(
        "--end-date", type=_parse_date, help="Optional bronze end date YYYY-MM-DD."
    )
    refresh.add_argument("--run-date", type=_parse_date, help="Archive run date YYYY-MM-DD.")
    refresh.add_argument(
        "--mock",
        action="store_true",
        help="Write mocked quote outputs during Bronze.",
    )
    refresh.add_argument(
        "--concurrency",
        type=_positive_int,
        default=2,
        help="Maximum parallel Bronze, Silver, and Gold workers. Defaults to 2.",
    )
    refresh_selector = refresh.add_mutually_exclusive_group()
    refresh_selector.add_argument(
        "--limit",
        type=_positive_int,
        help="Limit Bronze to the first N approved canonical ISINs.",
    )
    refresh_selector.add_argument(
        "--isin",
        help="Limit Bronze to one approved canonical ISIN.",
    )
    dry_run = subparsers.add_parser("dry-run", help="Run the deterministic mocked pipeline.")
    dry_run.add_argument(
        "--debug",
        action="store_true",
        default=argparse.SUPPRESS,
        help="Write verbose DEBUG logs.",
    )
    dry_run.add_argument("--root", default="lake", help="Lake root for generated artifacts.")
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    """Run the Founder command-line interface."""
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.command is None:
        print("founder")
        return
    setup_logging(debug=getattr(args, "debug", False))
    LOGGER.debug("parsed cli args command=%s", args.command)
    if args.command == "search":
        summary = run_search_workflow(
            root=Path(args.root),
            input_path=Path(args.input),
            query=args.query,
            search_run_id=args.search_run_id,
            run_date=args.run_date,
            approve=not args.no_approve,
        )
    elif args.command == "sync-eodhd-isins":
        summary = run_search_sync_isins_workflow(
            root=DEFAULT_ROOT,
            config_loader=load_eodhd_config,
            client_factory=EodhdClient,
        )
    elif args.command == "selection":
        summary = run_bronze_workflow(
            root=Path(args.root),
            config_loader=load_eodhd_config,
            client_factory=EodhdClient,
            run_id=args.run_id,
            start_date=args.start_date,
            end_date=args.end_date,
            run_date=args.run_date,
            mock=args.mock,
            concurrency=args.concurrency,
            limit=args.limit,
            isin=args.isin,
        )
    elif args.command == "silver":
        summary = run_silver_workflow(root=Path(args.root), concurrency=args.concurrency)
    elif args.command == "gold":
        summary = run_gold_workflow(root=Path(args.root), concurrency=args.concurrency)
    elif args.command == "evaluate":
        summary = run_evaluate_workflow(
            root=Path(args.root),
            evaluation_id=args.evaluation_id,
            portfolio_id=args.portfolio_id,
            objective=args.objective,
            optimize=args.optimize,
            walk_forward=args.walk_forward,
            rebalance=args.rebalance,
            frontier=args.frontier,
            tail_risk=args.tail_risk,
            run_id=args.run_id,
            train_window=args.train_window,
            test_window=args.test_window,
            schedule=args.schedule,
            grid_step=args.grid_step,
            max_weight=args.max_weight,
            target_returns=args.target_returns,
            confidence_level=args.confidence_level,
        )
    elif args.command == "refresh":
        summary = run_refresh_workflow(
            root=Path(args.root),
            config_loader=load_eodhd_config,
            client_factory=EodhdClient,
            run_id=args.run_id,
            start_date=args.start_date,
            end_date=args.end_date,
            run_date=args.run_date,
            mock=args.mock,
            concurrency=args.concurrency,
            limit=args.limit,
            isin=args.isin,
        )
    elif args.command == "dry-run":
        LOGGER.info("running dry-run root=%s", args.root)
        summary = run_dry_run(Path(args.root))
        LOGGER.info("dry-run complete root=%s", args.root)
    else:
        print("founder")
        return
    print(json.dumps(summary, sort_keys=True))


_generated_run_id = generated_run_id
