"""Lake table schema contracts."""

from __future__ import annotations

SCHEMAS: dict[str, tuple[str, ...]] = {
    "search_candidates": (
        "search_run_id",
        "query",
        "source_endpoint",
        "code",
        "exchange",
        "instrument_type",
        "country",
        "currency",
        "isin",
        "name",
        "normalized_name",
        "found_at",
    ),
    "canonical_universe": (
        "search_run_id",
        "isin",
        "code",
        "exchange",
        "instrument_type",
        "country",
        "currency",
        "name",
        "normalized_name",
        "selection_reason",
        "selected_for_bronze",
    ),
    "bronze_plan": ("run_id", "isin", "code", "exchange", "symbol", "start_date", "end_date"),
    "quotes": (
        "run_id",
        "isin",
        "code",
        "exchange",
        "date",
        "open",
        "high",
        "low",
        "close",
        "adjusted_close",
        "volume",
        "currency",
        "bronzed_at",
    ),
    "coverage": (
        "run_id",
        "isin",
        "code",
        "exchange",
        "first_quote_date",
        "last_quote_date",
        "observed_rows",
        "missing_periods",
        "next_bronze_start",
    ),
    "quote_gaps": (
        "run_id",
        "isin",
        "code",
        "exchange",
        "symbol",
        "data_type",
        "gap_type",
        "gap_start",
        "gap_end",
        "missing_dates",
    ),
    "errors": ("run_id", "code", "exchange", "endpoint", "error_type", "message"),
    "returns": ("isin", "exchange", "code", "date", "return"),
    "correlation": (
        "left_isin",
        "left_exchange",
        "left_code",
        "right_isin",
        "right_exchange",
        "right_code",
        "correlation",
    ),
    "covariance": (
        "left_isin",
        "left_exchange",
        "left_code",
        "right_isin",
        "right_exchange",
        "right_code",
        "covariance",
    ),
    "gold_runs": (
        "status",
        "isin",
        "exchange",
        "code",
        "input_last_quote_date",
        "input_snapshot_date",
        "input_listing_count",
        "completed_at",
    ),
    "return_matrix": (
        "evaluation_id",
        "date",
        "isin",
        "exchange",
        "code",
        "return",
    ),
    "asset_metrics": (
        "evaluation_id",
        "isin",
        "exchange",
        "code",
        "observation_count",
        "first_return_date",
        "last_return_date",
        "mean_return",
        "annualized_return",
        "annualized_volatility",
        "downside_deviation",
        "sharpe_ratio",
        "sortino_ratio",
    ),
    "portfolio_returns": (
        "evaluation_id",
        "portfolio_id",
        "date",
        "return",
        "cumulative_wealth",
    ),
    "drawdowns": (
        "evaluation_id",
        "portfolio_id",
        "date",
        "cumulative_wealth",
        "running_peak",
        "drawdown",
        "drawdown_duration",
        "recovery_duration",
        "is_recovered",
    ),
    "portfolio_metrics": (
        "evaluation_id",
        "portfolio_id",
        "objective",
        "annualized_return",
        "annualized_volatility",
        "sharpe_ratio",
        "sortino_ratio",
        "max_drawdown",
        "calmar_ratio",
        "ulcer_index",
        "turnover",
    ),
    "frontier_points": (
        "evaluation_id",
        "frontier_point_id",
        "target_return",
        "expected_return",
        "volatility",
        "sharpe_ratio",
        "is_feasible",
        "diagnostics",
    ),
    "frontier_weights": (
        "evaluation_id",
        "frontier_point_id",
        "isin",
        "exchange",
        "code",
        "weight",
    ),
    "optimized_weights": (
        "evaluation_id",
        "objective",
        "portfolio_id",
        "isin",
        "exchange",
        "code",
        "weight",
        "constraints",
        "diagnostics",
    ),
}


def required_fields(table_name: str) -> tuple[str, ...]:
    try:
        return SCHEMAS[table_name]
    except KeyError as error:
        raise ValueError(f"unknown schema: {table_name}") from error


def validate_fields(table_name: str, row: dict[str, object]) -> None:
    missing = [field for field in required_fields(table_name) if field not in row]
    if missing:
        raise ValueError(f"{table_name} row missing fields: {', '.join(missing)}")
