repos:
  - repo: local
    hooks:
      - id: camovar-quality-pr
        name: camovar quality pr
        entry: uv run camovar-quality pr
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: camovar-conventional-commit
        name: camovar conventional commit
        entry: uv run camovar-quality --commit-msg-file
        language: system
        stages: [commit-msg]